Repository woosuk-computer-engineering/curriculum, pull requests merged in 2020-09, with the labels that each got.

#2 [#1] refactor: 작업 양식 수정
  assets/logo/sw중심대학사업단.png
  assets/logo/충북대학교.png
  src/data.js
  src/data/certificate.js
  src/data/graphs_of_courses.js
  src/data/plan_future.js
Labels: 리팩토링

#6 [#5] feat: 과목수정 및 이수체계도 기능 추가
  src/data/computer_science.js
  src/data/graphs_of_courses.js
Labels: 기능수정, 기능추가

#9 [#3] feat:자격증추가
  src/data/certificate.js
Labels: 기능추가

#23 [#20] feat : 자격증 이미지삽입
  assets/자격증/cisco/ccie.svg
  assets/자격증/cisco/ccna.svg
  assets/자격증/cisco/ccnp.svg
  assets/자격증/linux/lpic.svg
  assets/자격증/linux/rhce.svg
  assets/자격증/ms/mcdba.svg
  assets/자격증/ms/mcp.svg
  assets/자격증/ms/mcse.svg
  assets/자격증/ms/mct.svg
  assets/자격증/ms/mos.svg
  assets/자격증/oracle/ocp.svg
  assets/자격증/oracle/모바일-프로그래밍.svg
  assets/자격증/oracle/운영체제의-이해.svg
  assets/자격증/oracle/웹-응용-프로그래밍.svg
  assets/자격증/oracle/자료구조와-문제해결.svg
  assets/자격증/oracle/자바프로그래밍.svg
  assets/자격증/sun/csa.svg
  assets/자격증/sun/iot-기술과-프로그래밍.svg
  assets/자격증/sun/scjp.svg
  assets/자격증/sun/scna.svg
  assets/자격증/sun/인공지능과-기계학습.svg
  assets/자격증/sun/정보기술의-이해.svg
  assets/자격증/sun/파이썬-프로그래밍.svg
  assets/자격증/국가공인자격(kait)/pc정비사.svg
  assets/자격증/국가공인자격(kait)/네트워크관리사.svg
  assets/자격증/국가공인자격(kait)/리눅스마스터.svg
  assets/자격증/국가기술자격증(q-net)/멀티미디어콘텐츠제작전문가.svg
  assets/자격증/국가기술자격증(q-net)/사무자동화산업기사.svg
  assets/자격증/국가기술자격증(q-net)/전자계산기기사.svg
  assets/자격증/국가기술자격증(q-net)/전자계산기조직응용기사.svg
  assets/자격증/국가기술자격증(q-net)/전자상거래관리사.svg
  assets/자격증/국가기술자격증(q-net)/정보보안기사.svg
  assets/자격증/국가기술자격증(q-net)/정보처리기사.svg
Labels: 기능추가

#24 [#22] feat: 아이콘 수정
  assets/진로/네트워크/네트워크-보안가.svg
  assets/진로/데이터베이스/db.svg
  assets/진로/데이터베이스/dba.svg
  assets/진로/데이터베이스/dbms-엔지니어.svg
  assets/진로/데이터베이스/튜너.svg
  assets/진로/프로그래밍/db-개발자.svg
  src/data/plan_future.js
Labels: 기능수정

#28 헤더 링크 및 학과 소개 수정
  assets/졸업-후-진로/네트워크/네트워크-보안가.svg
  assets/졸업-후-진로/네트워크/네트워크-설계자.svg
  assets/졸업-후-진로/네트워크/네트워크-엔지니어.svg
  assets/졸업-후-진로/데이터베이스/da.svg
  assets/졸업-후-진로/데이터베이스/dba.svg
  assets/졸업-후-진로/데이터베이스/dbms-엔지니어.svg
  assets/졸업-후-진로/데이터베이스/모델러.svg
  assets/졸업-후-진로/데이터베이스/튜너.svg
  assets/졸업-후-진로/시스템-서버/서버-관리자.svg
  assets/졸업-후-진로/시스템-서버/서버-엔지니어.svg
  assets/졸업-후-진로/시스템-서버/시스템-보안가.svg
  assets/졸업-후-진로/정보보안/모의-해킹-전문가.svg
  assets/졸업-후-진로/정보보안/보안-컨설턴트.svg
  assets/졸업-후-진로/정보보안/보안관제-전문가.svg
  assets/졸업-후-진로/정보보안/보안솔루션-개발자.svg
  assets/졸업-후-진로/정보보안/악성코드-분석전문가.svg
  assets/졸업-후-진로/정보보안/침해-대응-전문가(cert).svg
  assets/졸업-후-진로/프로그래밍/db-개발자.svg
  assets/졸업-후-진로/프로그래밍/게임-개발자.svg
  assets/졸업-후-진로/프로그래밍/네트워크-개발자.svg
  assets/졸업-후-진로/프로그래밍/보안-프로그래머.svg
  assets/졸업-후-진로/프로그래밍/앱-개발자.svg
  assets/졸업-후-진로/프로그래밍/웹-개발자.svg
  assets/졸업-후-진로/프로그래밍/응용-프로그래머.svg
  assets/졸업-후-진로/프로그래밍/컴포넌트-개발자.svg
  assets/취득-자격증/cisco/ccie.svg
  assets/취득-자격증/cisco/ccna.svg
  assets/취득-자격증/cisco/ccnp.svg
  assets/취득-자격증/linux/lpic.svg
  assets/취득-자격증/linux/rhce.svg
  assets/취득-자격증/ms/mcdba.svg
  assets/취득-자격증/ms/mcp.svg
  assets/취득-자격증/ms/mcse.svg
  assets/취득-자격증/ms/mct.svg
  assets/취득-자격증/ms/mos.svg
  assets/취득-자격증/oracle/ocp.svg
  assets/취득-자격증/sun/csa.svg
  assets/취득-자격증/sun/scjp.svg
  assets/취득-자격증/sun/scna.svg
  assets/취득-자격증/국가공인자격(kait)/pc정비사.svg
  assets/취득-자격증/국가공인자격(kait)/네트워크관리사.svg
  assets/취득-자격증/국가공인자격(kait)/리눅스마스터.svg
  assets/취득-자격증/국가기술자격증(q-net)/멀티미디어콘텐츠제작전문가.svg
  assets/취득-자격증/국가기술자격증(q-net)/사무자동화산업기사.svg
  assets/취득-자격증/국가기술자격증(q-net)/전자계산기기사.svg
  assets/취득-자격증/국가기술자격증(q-net)/전자계산기조직응용기사.svg
  assets/취득-자격증/국가기술자격증(q-net)/전자상거래관리사.svg
  assets/취득-자격증/국가기술자격증(q-net)/정보보안기사.svg
  assets/취득-자격증/국가기술자격증(q-net)/정보처리기사.svg
  src/app.js
  src/data/certificate.js
  src/data/plan_future.js
  src/molecules/collection.js
  src/util/open-help.js
Labels: 기능수정
